# Generated by Django 2.2.3 on 2019-09-14 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('acquired_by_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='points.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturemodel',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomModel',
        ),
        migrations.DeleteModel(
            name='LectureModel',
        ),
    ]
