# Generated by Django 2.2.3 on 2019-09-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20190914_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerModel',
        ),
    ]
