# Generated by Django 2.2.3 on 2019-09-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20190914_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermodel',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='pointmodel',
            options={'verbose_name': 'Points', 'verbose_name_plural': 'Points'},
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='ticket_id',
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='acquired_by_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_set', to='points.PlayerModel'),
        ),
    ]
