# Generated by Django 2.2.3 on 2019-09-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20190914_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPointsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pointmodel',
            name='type_of_points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_set', to='points.TypeOfPointsModel'),
        ),
    ]
