# Generated by Django 2.2.3 on 2019-09-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20190914_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointmodel',
            name='type_of_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_set', to='points.TypeOfPointsModel'),
        ),
    ]
