# Generated by Django 3.2.13 on 2022-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMSPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="The public url to the page, example: https://website.com/YOUR_SLUG_HERE/",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("public_content", models.TextField(blank=True, max_length=40000)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SponsorsCarousel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("image", models.ImageField(upload_to="sponsors/")),
                ("description", models.CharField(blank=True, max_length=100)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
