# Generated by Django 2.2.3 on 2019-07-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protected_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedfiles',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_content_type', to='protected_files.FileContentTypes'),
        ),
    ]
