# Generated by Django 2.2.3 on 2019-09-14 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import protected_files.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protected_files', '0002_auto_20190718_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedfiles',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_file_content_type', to='protected_files.FileContentTypes'),
        ),
        migrations.CreateModel(
            name='PublicFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modify', models.DateTimeField(blank=True, editable=False, null=True)),
                ('file', models.FileField(upload_to='public/', validators=[protected_files.validators.validate_file_size_and_content_type])),
                ('added_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_content_type', to='protected_files.FileContentTypes')),
                ('modify_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public File',
                'verbose_name_plural': 'Public User Files',
            },
        ),
    ]
