# Generated by Django 2.2.3 on 2019-09-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protected_files', '0003_auto_20190914_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectedfiles',
            options={'verbose_name': 'Protected file', 'verbose_name_plural': 'Protected files'},
        ),
        migrations.AlterModelOptions(
            name='publicfiles',
            options={'verbose_name': 'Public file', 'verbose_name_plural': 'Public files'},
        ),
    ]
