# Generated by Django 2.2.3 on 2019-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturemodel',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='roommodel',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='lecturemodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
