# Generated by Django 2.2.3 on 2019-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='The public url to the page, example: https://website.com/YOUR_SLUG_HERE/', max_length=120, unique=True)),
                ('public_content', models.TextField(blank=True, max_length=40000)),
            ],
        ),
    ]
