# Generated by Django 2.2.3 on 2019-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorsCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsors/')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
