# Generated by Django 2.2.3 on 2019-09-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sponsorscarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorscarousel',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='sponsorscarousel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
