# Generated by Django 2.2.3 on 2019-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190915_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorscarousel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
