# Generated by Django 2.2.3 on 2019-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sponsorscarousel_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
